### PR TITLE
Fix -Wsign-compare warnings

### PR DESCRIPTION
**Pull request by tetsuok**
Currently, we see lots of warnings when building with `-DBACKEND=cuda`.
This attempts to fix -Wsign-compare warnings.

---
This change is [Reviewable](https://reviewable.io/reviews/clab/dynet/883)

### CODE REVIEW

**Comment by tetsuok** [comment]
Sure. I'd like to fix the other types of warnings in a separate PR.
Also, I think `_dynet.cpp` is the file automatically generated by Cython.

**Comment by xunzhang** [comment]
ok, totally fine. I know, could we generate no-warning `_dynet.cpp` in some way? Not sure though.

**Comment by tetsuok** [comment]
Sorry I don't know right now. I was actually wondering, too.

**Comment by xunzhang** [comment]
Never mind, let's push it back then.

**Comment by tetsuok** [comment]
As far as I know, what we can do now is to disable particular warnings in compiling Cythoned files.
Please take a look at #887.

**Pull request merged**
