### PR TITLE
Continuous integration for Windows using AppVeyor

### PR DESCRIPTION
**Pull request by danielhers**
Someone with write access to clab/dynet needs to create a project on https://ci.appveyor.com/projects/new for this to take effect.

### CODE REVIEW

**Comment by neubig** [comment]
I think this did it: https://ci.appveyor.com/project/neubig/dynet

But I'm not sure how this works, or how we could, for example, test this branch.

**Comment by danielhers** [comment]
Thanks. But I think it should be clab/dynet rather than neubig/dynet (you should see it in the list too).
AppVeyor is similar to Travis CI: once enabled, it will run for each push and PR, and test it on Windows. Otherwise there's no change in this PR to DyNet itself.

**Comment by danielhers** [comment]
I commented out some of the tests because I couldn't figure out why they failed on Windows, but it still tests the build itself so I think it's worthwhile. And I fixed a compile error in one of the tests that's specific to MSVC.

**Comment by neubig** [comment]
OK, let's save testing on Windows for another PR. (Not sure if @mattr1 would be able to help with this?)

**Comment by mattr1** [comment]
Sure, I can help out in a couple of weeks. I’m actually on paternity leave right now ☺

**Comment by neubig** [comment]
Oh, congratulations :) No hurry at all of course.

**Comment by mattr1** [comment]
@danielhers: Thank you so much for doing this! Windows CI will save myself and others a lot of time fixing little issue that would pop up regularly and break the MSVC compile. I can't express how great it is to come back after 6 weeks, do a pull, and have it compile without a hitch. Thank you!

Is there any work that still needs to be done on this? Above you said some of the tests were failing? Or did those get fixed?

**Comment by neubig** [comment]
@mattr1 They are disabled on AppVeyor, so we're not sure if they're fixed or not. If you could take a look and see if they pass that'd be appreciated.

**Comment by mattr1** [comment]
Okay, I'll take a look. Looking at the .travis files, I don't see anywhere that TravisCI is running the tests either (I assume we are talking about test-dim, test-dynet, test-exec, test-io, ...). Is that correct? Also, @danielhers , what is the best way for testing new appveyor configurations? I can modify it and push in a branch and then wait for AppVeyor to run, but is there a more direct way to do it?

**Comment by mattr1** [comment]
sorry, never mind about where TravisCI is testing, I found the "make test" line in test_dynet.sh.

**Comment by danielhers** [comment]
Correct, just the C++ tests are disabled on AppVeyor.
About testing configurations, the best way I found is pushing to a branch. But you can at least validate the file format in https://ci.appveyor.com/tools/validate-yaml

**Comment by danielhers** [comment]
Oh, and also Python 2 is disabled.

**Comment by mattr1** [comment]
unit tests added in PR https://github.com/clab/dynet/pull/1013

**Pull request merged**
