### PR TITLE
To make the DeviceMemPoolSizes constructor more robust

### PR DESCRIPTION
**Pull request by MalcolmSun**
Add `cerr<<The format of --dynet-mem is invalid` and `abort()` to avoid program encoutering some unexpected problems when the --dynet-mem's length  is not 1 or 3.

### CODE REVIEW

**Comment by neubig** [comment]
Thanks! But we're actually in the process of changing to throwing errors instead of using abort (https://github.com/clab/dynet/issues/139). Would you mind changing the format?

**Comment by MalcolmSun** [comment]
Ok, I will change the format, then create a new PR.

**Comment by MalcolmSun** [comment]
In the new commit, I have changed `abort()` to `throw`. `invalid_argument_format` exception class extends `std::invalid_argument`.

**Comment by MalcolmSun** [comment]
In the new  commit, I have changed the format and keep it consistent with code style.

**Comment by neubig** [comment]
Great, thanks!

**Pull request merged**
