### PR TITLE
Simplify training interface by removing weight decay and scaling

### PR DESCRIPTION
**Pull request by neubig**
There is some confusion regarding the interface of the "Trainer" class:
https://github.com/clab/dynet/issues/641
https://github.com/clab/dynet/issues/684

I agree that it's difficult to understand. This commit removes the rate decay and gradient scaling functionality that implicitly changes the learning rate in non-transparent ways. Here is an example of the before/after behavior:

*Rate Decay Before*

    // At beginning of training
    Trainer trainer(initial_learning_rate, rate_decay)
    // After every epoch
    trainer.update_epoch()

*Rate Decay After*

    // At beginning of training
    Trainer trainer(initial_learning_rate)
    // After every epoch
    trainer.learning_rate /= (1 - rate_decay)

*Gradient Scaling Before*:

    cg.backward(loss)
    trainer.update(scaling_factor)

*Gradient Scaling After*:

    cg.backward(loss * scaling_factor)
    trainer.update()

### CODE REVIEW

**Comment by liesun1994** [comment]
I am wondering  if lamtram need to be modified with the issues pulled.

**Comment by liesun1994** [comment]
When I am running lamtram， it may occurs Trainer::update_epoch has been deprecated and doesn't do anything. Please remove it from your code, and control the learning rate of the trainer directly, for example by: 'trainer.learning_rate /= (1 - rate_decay)', see https://github.com/clab/dynet/pull/695 for details .

**Comment by yuvalpinter** [comment]
I can't seem to be able to run the `trainer.learning_rate /= (1 - rate_decay)` code. It gives me the following error: `TypeError: 'property' object is not callable`.
This happens for both `MomentumSGDTrainer` and `AdamTrainer`.

**Comment by shuheik** [comment]
Shouldn't it be 
`trainer.learning_rate *= (1 - rate_decay)` or 
`trainer.learning_rate /= (1 + rate_decay)`
instead of 
`trainer.learning_rate /= (1 - rate_decay)`?

I assume rate_decay to be some small positive value and dividing by (1- rate_decay) would make learning_rate grow larger.

**Pull request merged**
