### PR TITLE
Stable logistic

### PR DESCRIPTION
**Pull request by pmichel31415**
Stabilize logistic function computation (so that there is no negative output)

Addresses #1090

### CODE REVIEW

**Comment by redpony** [comment]
This isn’t going to be SIMD friendly- you should check the speed on CPU for
large batches.

**Comment by redpony** [comment]
Actually, better to check the generated assembly to see if the vectorised
ops are getting generated.

**Comment by neubig** [comment]
Taking a look at this now, and indeed this causes a significant speed regression (0m1.565s -> 0m16.911s) using the following code.

    import dynet as dy
    
    for _ in range(10):
      dy.renew_cg()
      x = dy.zeros((10000000,))
      for i in range(20):
        x = dy.logistic(x)
      y = dy.sum_elems(x)
      print(y.value())

@pmichel31415 can we make a SIMD-friendly version by just adding `max(0, val)` to the SIMD functors?

**Comment by pmichel31415** [comment]
Thanks for running those tests! I didn't want to use a rectifier initially because in the use case described in #1090 (and in my own code) the intent is to use `log(sigmoid(x))` which might end up returning NaN.

I'll implement this nonetheless (maybe as `1/(e+e^{-x})` instead), but I wont have time to do it his week unfortunately.

**Comment by neubig** [comment]
We now have a bunch of new examples of functors. Is it worth revisiting this PR?

**Comment by redpony** [comment]
I think the right way to implement this is to do two custom ops, one for
the x<0 case and the other for the x>=0 case, then you the select operation
together with those two. I looked into implementing select and the two
operators together in one op and using the packet operations myself, but
the way Eigen is designed makes this difficult to do (basically, you need
to have access to the vector size of the packet type, which could have been
a template parameter but isn't).

I assume this will be faster than the non-packet version (if if you're
doing both the -x and x cases every time), but this would need to be
empirically looked at.

**Comment by pmichel31415** [comment]
Thanks for the tips, I'll definitely do that. Chris, is there a documentation/reference manual online for simd operations in Eigen?

I'll probably close this PR and open a new one with the simd implementation

**Comment by redpony** [comment]
Unfortunately no, you just have to read the code. Look for a file called
“packet_math.h” or something like that. The functions are called things
like pmul, padd, pdiv, pexp, etc.

**Pull request closed without merging**
