### PR TITLE
Save/load the optimizer state

### PR DESCRIPTION
**Pull request by FilippoC**
Hi,
I need to adress issue  #785 for my work so I thought I could contribute upstream.

I started to implement methods to save/load the parameters of an optimizer (hyperparameters+momentum etc) in C++. The API is very simple:

```
void Trainer::save_state(std::ostream& os);
void Trainer::load_state(std::istream& is, bool restore_hyperparams);
```

Todo:
- ~~at the moment, when saving params, I use TensorTools::access_element(sp.h, i) to access each element of the tensor individually: this may be really slow, especially on GPU. Is there an alternative?~~ replaced with dynet::as_vector(sp.h)
- try to use templates from dynet/io.h instead of my write/read functions
- .update() should have been called at least once before saving/loading. This is a big issue, I'll try to fix this as soon as possible
- unit testing
- python API: I do not use the python version of dynet so I may struggle to implement this

Please, tell me if you are intersted in this contribution. If yes, I'll try to fix the problems listed above.

Best,
Caio Corro

### CODE REVIEW

**Comment by pmichel31415** [comment]
Hi @FilippoC thanks a lot for the contribution. I think fixing the `.update()` thing and adding unit tests is the most important, we can look at the python bindings later.

I'm a bit busy with conference deadlines right now but I'll take a closer look after thursday.

**Comment by FilippoC** [comment]
Hi, I am a little bit busy this week too, I'll update this next week!

**Comment by FilippoC** [comment]
So I make a better version of this, but before commiting I want to also build unit tests.
Unfortunately, I am not able to build any test: make test-io for example fails. The error is from the linker, it does not find any symbol related to dynet. Is there something special to build/run tests?

Here is how I buile makefiles (and if it matter, I use g++ 7 and do not have cuda on my dev computer):
`cmake .. -DEIGEN3_INCLUDE_DIR=/Users/filippo/repos/eigen -DENABLE_BOOST=ON -DBOOST_ROOT:PATHNAME=/usr/local/Cellar/boost/1.67.0_1 -DBoost_LIBRARY_DIRS:FILEPATH=/usr/local/Cellar/boost/1.67.0_1/lib -DBoost_NO_BOOST_CMAKE=TRUE -DBoost_NO_SYSTEM_PATHS=TRUE`

When running `make test-io`:
 ```
 1 Undefined symbols for architecture x86_64:
  2   "dynet::TextFileSaver::save(dynet::ParameterCollection const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
  3       io_test::test_save1_perf::test_method()      in test-io.cc.o
  4       io_test::test_save2_perf::test_method()      in test-io.cc.o
  5       io_test::test_save_populate_pc::test_method()      in test-io.cc.o
  6       io_test::test_save_populate_sub_pc::test_method()      in test-io.cc.o
  7       io_test::test_load1_perf::test_method()      in test-io.cc.o
  8       io_test::test_load2_perf::test_method()      in test-io.cc.o
  9       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 10       ...
 11   "dynet::TextFileSaver::TextFileSaver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)", referenced from:
 12       io_test::test_save1_perf::test_method()      in test-io.cc.o
 13       io_test::test_save2_perf::test_method()      in test-io.cc.o
 14       io_test::test_save_populate_pc::test_method()      in test-io.cc.o
 15       io_test::test_save_populate_sub_pc::test_method()      in test-io.cc.o
 16       io_test::test_load1_perf::test_method()      in test-io.cc.o
 17       io_test::test_load2_perf::test_method()      in test-io.cc.o
 18       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 19       ...
 20   "dynet::TextFileLoader::load_param(dynet::ParameterCollection&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
 21       io_test::test_save_load_parameter::test_method()      in test-io.cc.o
 22       io_test::test_save_load_parameter_nonzerograd::test_method()      in test-io.cc.o
 23   "dynet::TextFileLoader::load_lookup_param(dynet::ParameterCollection&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
 24       io_test::test_save_load_parameter::test_method()      in test-io.cc.o
 25       io_test::test_save_load_parameter_nonzerograd::test_method()      in test-io.cc.o
 26   "dynet::TextFileLoader::populate(dynet::LookupParameter&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
 27       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 28   "dynet::TextFileLoader::populate(dynet::ParameterCollection&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
 29       io_test::test_save_populate_pc::test_method()      in test-io.cc.o
 30       io_test::test_save_populate_sub_pc::test_method()      in test-io.cc.o
 31   "dynet::TextFileLoader::populate(dynet::Parameter&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
 32       io_test::test_load1_perf::test_method()      in test-io.cc.o
 33       io_test::test_load2_perf::test_method()      in test-io.cc.o
 34       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 35   "dynet::TextFileLoader::TextFileLoader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
 36       io_test::test_save_populate_pc::test_method()      in test-io.cc.o
 37       io_test::test_save_populate_sub_pc::test_method()      in test-io.cc.o
 38       io_test::test_load1_perf::test_method()      in test-io.cc.o
 39       io_test::test_load2_perf::test_method()      in test-io.cc.o
 40       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 41       io_test::test_save_load_parameter::test_method()      in test-io.cc.o
 42       io_test::test_save_load_parameter_nonzerograd::test_method()      in test-io.cc.o
 43       ...
 44   "dynet::ParameterCollection::add_parameters(dynet::Dim const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dynet::Device*)", referenced from:
 45       io_test::test_save_populate_pc::test_method()      in test-io.cc.o
 46       io_test::test_save_populate_sub_pc::test_method()      in test-io.cc.o
 47       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 48       io_test::test_save_load_parameter::test_method()      in test-io.cc.o
 49       io_test::test_save_load_parameter_nonzerograd::test_method()      in test-io.cc.o
 50   "dynet::ParameterCollection::add_parameters(dynet::Dim const&, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dynet::Device*)", referenced from:
 51       io_test::test_save1_perf::test_method()      in test-io.cc.o
 52       io_test::test_save2_perf::test_method()      in test-io.cc.o
 53       io_test::test_save_populate_pc::test_method()      in test-io.cc.o
 54       io_test::test_save_populate_sub_pc::test_method()      in test-io.cc.o
 55       io_test::test_load1_perf::test_method()      in test-io.cc.o
 56       io_test::test_load2_perf::test_method()      in test-io.cc.o
 57       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 58       ...
 59   "dynet::ParameterCollection::add_subcollection(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)", referenced from:
 60       io_test::test_save_populate_sub_pc::test_method()      in test-io.cc.o
 61   "dynet::ParameterCollection::add_lookup_parameters(unsigned int, dynet::Dim const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dynet::Device*)", referenced from:
 62       io_test::test_save_populate_pc::test_method()      in test-io.cc.o
 63       io_test::test_save_populate_sub_pc::test_method()      in test-io.cc.o
 64       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 65       io_test::test_save_load_parameter::test_method()      in test-io.cc.o
 66       io_test::test_save_load_parameter_nonzerograd::test_method()      in test-io.cc.o
 67   "dynet::operator<<(std::basic_ostream<char, std::char_traits<char> >&, dynet::Dim const&)", referenced from:
 68       boost::unit_test::lazy_ostream_impl<boost::unit_test::lazy_ostream, boost::test_tools::tt_detail::print_helper_t<dynet::Dim>, boost::test_tools::tt_detail::print_helper_t<dynet::Dim> const&>::operator()(std::basic_ostream<char, std::char_traits<char> >&) const     in test-io.cc.o
 69   "dynet::LookupParameter::get_fullname[abi:cxx11]() const", referenced from:
 70       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 71       io_test::test_save_load_parameter::test_method()      in test-io.cc.o
 72       io_test::test_save_load_parameter_nonzerograd::test_method()      in test-io.cc.o
 73   "dynet::Parameter::get_fullname[abi:cxx11]() const", referenced from:
 74       io_test::test_load1_perf::test_method()      in test-io.cc.o
 75       io_test::test_load2_perf::test_method()      in test-io.cc.o
 76       io_test::test_save_populate_parameter::test_method()      in test-io.cc.o
 77       io_test::test_save_load_parameter::test_method()      in test-io.cc.o
 78       io_test::test_save_load_parameter_nonzerograd::test_method()      in test-io.cc.o
 79 ld: symbol(s) not found for architecture x86_64
 80 collect2: error: ld returned 1 exit status
 81 make[3]: *** [tests/test-io] Error 1
 82 make[2]: *** [tests/CMakeFiles/test-io.dir/all] Error 2
 83 make[1]: *** [tests/CMakeFiles/test-io.dir/rule] Error 2
 84 make: *** [test-io] Error 2
```

**Comment by pmichel31415** [comment]
Maybe that's related if you're on Mac: https://walton.io/boost-v1-62-0-on-macos-sierra-9af5639f99b3 ?

Did you compile boost w/ the same compiler as dynet? Personally I've only ever built dynet on linux or windows and I've never had this problem

**Comment by FilippoC** [comment]
I installed boost from from homebrew but I used -cc=g++-7 to compile it with g++. Strange. Well I'll just code the unit test from one of the cluster of the lab. I'll try to have this ready in the beginning of next week!

**Comment by FilippoC** [comment]
Hi,

I updated the code with a clean API + unit testing. Everything should work now.

There is however one problem with unit testing of the EGTrainer: my test assumes that optimizer.update() changes the parameters of the network (and the output of the network). However the EGTrainer does not do that...is this the expected result?
Actually, in the test of the optimizer, it does not check that the update results in a decrease of the output of the network: https://github.com/clab/dynet/blob/master/tests/test-trainers.cc#L101
which is different for other optimizers.

**Comment by FilippoC** [comment]
It seems that travis failed because it cannot fetch files from the ubuntu website: https://travis-ci.org/clab/dynet/jobs/436045112
```
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/universe/b/boost1.55/libboost-test1.55-dev_1.55.0-1_amd64.deb  503  Service Unavailable [IP: 35.192.35.27 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command ".travis/install_dependencies.sh" failed 3 times.
The command "travis_retry .travis/install_dependencies.sh" failed and exited with 100 during .
```

**Comment by pmichel31415** [comment]
Sounds like a transient failure, I've restarted the job

**Pull request merged**
