### PR TITLE
Add NoneType assert for list arguments in _dynet.pyx.

### PR DESCRIPTION
**Pull request by xunzhang**
Address https://github.com/clab/dynet/issues/1114 and https://github.com/clab/dynet/issues/1124.

### CODE REVIEW

**Comment by neubig** [comment]
I think this is good, but it will touch a lot of programs. Just to be super-safe, could you try running the Python treenn benchmark here to make sure there isn't a significant performance regression?

https://github.com/neulab/dynet-benchmark/

**Comment by xunzhang** [comment]
Sure, will do.

**Comment by xunzhang** [comment]
I tested the treenn bench under CPU environment, see the results below:
```
$ python ./dynet-py/treenn.py --dynet-seed 2 32 32 0 600
# original
acc=0.4142, time=61.0756, sent_per_sec=139.8922
acc=0.4505, time=153.0769, sent_per_sec=111.6301
acc=0.4405, time=245.4292, sent_per_sec=104.4374
acc=0.4578, time=336.3393, sent_per_sec=101.6117
acc=0.4496, time=427.2538, sent_per_sec=99.9874
acc=0.4623, time=517.9566, sent_per_sec=98.9736
acc=0.4478, time=609.0355, sent_per_sec=98.2012

# with modification
acc=0.4287, time=59.2697, sent_per_sec=144.1547
acc=0.4487, time=157.1929, sent_per_sec=108.7072
acc=0.4405, time=253.8856, sent_per_sec=100.9589
acc=0.4414, time=344.4971, sent_per_sec=99.2055
acc=0.4460, time=438.2475, sent_per_sec=97.4792
acc=0.4550, time=532.6741, sent_per_sec=96.2390
acc=0.4351, time=626.8390, sent_per_sec=95.4121
```

```
$ python ./dynet-py/treenn.py --dynet-seed 2 128 128 0 600

# original
acc=0.4351, time=234.5920, sent_per_sec=36.4207
acc=0.4596, time=613.3140, sent_per_sec=27.8617

# with modification
acc=0.4151, time=241.8965, sent_per_sec=35.3209
acc=0.4632, time=619.9679, sent_per_sec=27.5627
```

```
# test_assert.py
def foo(xs):
    for x in xs: 
        assert x, "EMPTY"

arg = [i for i in xrange(1, 101)] # suppose 100 invokes of foo in each construction
for i in xrange(1000000): # 100 epoch * 10000 samples
    foo(arg)

$ time python test-assert.py
real	0m2.269s
user	0m2.228s
sys	0m0.024s
```

I only tested without autobatch, I think it will slow down the performance a little bit but not much. What do you think @neubig ?

**Comment by neubig** [comment]
Thanks! I think this is acceptable.

**Pull request merged**
