### PR TITLE
Restart method for optimizers

### PR DESCRIPTION
**Pull request by pmichel31415**
This adds a restart method to optimizers to reinitialize the momentum/rescaling parameters to 0.

Also adds python bindings

### CODE REVIEW

**Comment by neubig** [comment]
Thanks! Does this have any advantage over just calling the constructor and creating a new trainer?

**Comment by pmichel31415** [comment]
Does the memory of shadow-parameters get freed properly? I assumed it wasn't the case (like for standard parameters), hence it's more efficient to keep the same shadowparams and just reset their value)

**Comment by neubig** [comment]
That may be the case. Thanks for the clarification!

**Comment by pmichel31415** [comment]
OK I also added the option of setting a new learning rate as an argument.

I added a correctness test for the MomentumSGD which required making the velocity shadow-param public but I think that's OK.

Anyway for me it's good to merge once the tests are done

**Pull request merged**
