### PR TITLE
Softmax across rows

### PR DESCRIPTION
**Pull request by msperber**
- Introduce a softmax operator across rows, rather than columns as in the standard softmax.
- Both the softmax() and softmax_rows() are improved to use scratch memory rather than auxiliary memory.

Rather than introducing a new operator, I first tried to add a "dimension" parameter to the softmax that defaults to d=1, but that introduced inconsistency because softmax is also supposed to work for a vector input (for which d=1 makes no sense), so I went with the new operator instead.

### CODE REVIEW

**Comment by neubig** [comment]
Recently I've been trying to avoid "_rows" and instead going with "_dim" that allows you to specify an arbitrary dimension. Could you take a look at `logsumexp_dim`? I think it should be pretty simple to add the ability to specify a dimension to the `softmax` (and `logsoftmax`) functions. This has the added advantage of not adding more functions to the API.

**Comment by msperber** [comment]
Sure, so we would basically have something like this?
- softmax_dim(e, d)
- softmax(e) -> softmax_dim(e,0) if e is a vector, or softmax_dim(e,1) if e is a matrix?

**Comment by neubig** [comment]
I was just thinking of something like `softmax(e, d=0)`.

When we do our long-needed renaming of functions, I think we need to separate the componentwise operations (e.g. operations across expressions where each component is subject to that operation), and dimension-wise operations (operations that reduce or calculate along dimensions). `logsumexp` was already defined as a componentwise operation, so I needed to make `logsumexp_dim`. `softmax` on the other hand, is already a dimensionwise operation, and it doesn't have a componentwise version, so we can just add specifying the dimension to softmax.

**Comment by neubig** [comment]
(see here: https://github.com/clab/dynet/issues/940). This will be a lot of work to re-design though, so this pull request, let's just make a minimal modification while being consistent with the current functions.

**Comment by msperber** [comment]
Yes, that makes sense to me. But doing this for softmax would break existing code that uses softmax and force people to change their call from softmax(e) to softmax(e,d=1). If that's ok, I will push a commit.

**Comment by neubig** [comment]
No, softmax is currently done over columns, which means we need to reduce over rows. `d` should be the dimension over which we are calculating the denominator.

**Comment by msperber** [comment]
Ok got it, this should be ready then.

**Comment by neubig** [comment]
Thanks!

**Pull request merged**
