### PR TITLE
Add ipython notebooks to the docs

### PR DESCRIPTION
**Pull request by pmichel31415**
Notable changes : 

- Tutorials reorganized in docs, c++ and python are separated
- ipython notebooks from examples/tutorials are included in the python docs (if it doesn't break readthedocs   *fingers crossed*
- The ipython notebooks have been slightly modified to fit in the doc hierarchy. Most headers are downsized from 1 level in markdown

N.B. : this PR is redundant with #211

### CODE REVIEW

**Comment by yoavg** [comment]
Is there a way to see how the docs would look like after merging the PR?

**Comment by pmichel31415** [comment]
For lack of a better medium, here are screen captures from my local version (don't mind the ugly default theme)

---
Global menu (in index.rst)

menu
---

Tutorial menu (tutorial.rst)

menu_tuto
---

Example of a notebook

notebook

**Comment by yoavg** [comment]
Looks good, thanks.
Just to verify, the tutorials notebooks still remain at the previous location as well, right?

And one tiny addition before I merge: could you please add a link also to https://github.com/clab/dynet_tutorial_examples ?
we had it linked from the main page before but it got dropped at some point..

**Comment by pmichel31415** [comment]
Yes, the solution for now is to create a symlink to the notebooks during the doc compilation. This is problematic for windows but it's the best I could do with sphinx' limitations.

Thank you for the link I'll add it, you can merge after my next push

**Pull request merged**
