### PR TITLE
Python 3 bugfix

### PR DESCRIPTION
**Pull request by mitchellstern**

### CODE REVIEW

**Comment by yoavg** [comment]
Range creates a list in python 2 and is slower. Python 3 support is nice to have, but need to quantify the performance hit we get because of this.

**Comment by mitchellstern** [comment]
Cython seems to be able to compile `xrange` even for Python 3, though I'm not sure how it's handled under the hood -- perhaps this commit can be omitted. The other issue is a genuine bug for Python 3 though; deserialization of `BiRNNBuilder`s isn't working correctly at the moment.

**Comment by yoavg** [comment]
If cython handles the xrange for python 3, lets keep it as xrange. The list in the serialization is indeed important (and in a speed where speed doesn't matter at all) so lets fix only that. Can you change the pull request to include only the list fix?

**Comment by mitchellstern** [comment]
Done! Now only the bugfix is included.

**Pull request merged**
