### PR TITLE
reduce .cu include files

### PR DESCRIPTION
**Pull request by xunzhang**
Part of https://github.com/clab/dynet/issues/522

### CODE REVIEW

**Comment by neubig** [comment]
I think this will significantly increase compile time on GPU because it will cause `gpu-nodes-operators.cu` to take a long time, and not allow for multithreading, right? Also, this file will likely be re-compiled any time we make a change to one of the included `.cc` files.

I agree that we'd like to remove all the extra `gpu-...` files though. Perhaps we can find some way to generate them automatically using `cmake`, or some way to specify that `nvcc` should compile `.cc` files.

**Comment by xunzhang** [comment]
@neubig good advice. Done using auto generated file solution.

**Comment by xunzhang** [comment]
This pull request keeps the same compile time as https://github.com/clab/dynet/pull/679. One question here, I noticed that after https://github.com/clab/dynet/pull/679, on my local dev machine using `make -j8`, there is no obvious performance gain under GPU mode. Is that expected? What's your result? Thanks.

**Comment by mattr1** [comment]
@xunzhang: If it's not too much trouble, I think the CMakefile would be much improved if the list of gpu files is not duplicated (in dynet_gpu_SRCS and the foreach loop). Would it be possible to have the foreach append the newly created file to dynet_gpu_SRCS instead? Something like "list(APPEND dynet_gpu_SRCS ${PROJECT_BINARY_DIR}/dynet/gpu-${FILENAME}.cu". Or, I can do this after the PR is merged if you prefer.

**Comment by mattr1** [comment]
Having the many small .cu files compiled independently has significantly increased the compile time of gdynet on MSVC (from 4.5 minutes for a single monolithic .cu file to 18 minutes for the current split of 30 files), because MSVC (unfortunately) doesn't do parallel building of that part of the compilation (they are custom actions calling nvcc, rather than using the built-in compiler). 

I consider that MSVC's fault. However, note there is a lot of overhead in compiling each .cu file because the majority of the code is Eigen that is getting parsed and compiled over and over. That 4x increase in compile time is comparing two sequential compiles, so it shows how much overhead there is. I would imagine this overhead is also hurting the parallel Linux build, and that it would probably be faster to build in Linux if there were just, say, 4-8 files built in parallel instead of the current 30. This would also have the side-benefit of speeding up the MSVC compile.

**Comment by neubig** [comment]
P.S., and I agree that it'd be better to not duplicate the list of files twice in the CMakeLists file.

**Comment by mattr1** [comment]
Agreed on the difficulty of balancing the goals. Though, my experience so far is that changes often affect something like dynet.h or model.h and so the entire gdynet has to get recompiled anyway.

I have found that if I compile only for the latest CUDA architecture, I get something like a 2x speedup in compilation time. I see you opened an issue to track that here: https://github.com/clab/dynet/issues/661. I'll comment there.

At the risk of adding complexity, I could imagine adding a CMake parameter setting that switches between compiling each .cu individually, vs. compiling 4-8 of them, vs. compiling one monolithic one. The default should probably be whatever is fastest for users to just do a single compile, but then developers could modify it to suit their needs. Something like NUM_PARALLEL_CUDA_COMPILES or something like that. I can take a look at that if you think this is a good direction -- it'll probably involve a few lines of CMake doing math and modular arithmetic and appending to files.

**Comment by xunzhang** [comment]
@mattr1 thanks for the comment, very helpful! Modified with removing the duplicate declaration of filenames.

**Comment by neubig** [comment]
Thanks, I'll merge this for now. @mattr1, I think that for now having an option about whether to perform parallel compilation of the `gpu-nodes-*.cu` classes, or more broadly, whether to perform `nodes-*.cc` in parallel would be reasonable, at least for the time being. Also on Travis CI or when installing through, having `nodes-*.cc` compile as one big file might be useful as well, as I don't believe these are making heavy use of multi-threading.

**Comment by mattr1** [comment]
Okay, I'll take a look.

**Comment by mattr1** [comment]
Created PR https://github.com/clab/dynet/pull/689 to allow merging GPU compilation into k files.

**Pull request merged**
