### PR TITLE
Added next-word-prediction, save and load model

### PR DESCRIPTION
**Pull request by vicmak**
Added an explicit function to get a softmax-ed distribution over the vocabulary, based on the prefix-context.
Added two functions for saving/loading a model to/from disk.

### CODE REVIEW

**Comment by neubig** [comment]
Thanks for this! Just a few quick requests:

* Following the DyNet coding conventions (http://dynet.readthedocs.io/en/latest/code_style.html) could you change all function names (including BuildLMGraph) to snake case, where all words are lowercase and separated by an underbar.
* The softmax calculation shouldn't be performed at every step, but only at the end of the loop, because we're not using it every time. This is important for efficiency, because softmax calculation is expensive. Let's move this calculation out of the inner loop. Also, the probabilities probably shouldn't be named `err`. What about something like `prob`?
* This is purely an aesthetic thing, but can we change `save2disk` to `save_to_disc`? "to" seems to go better with "from".

**Comment by vicmak** [comment]
Changed according to review.
Thanks for the useful comments.

**Comment by neubig** [comment]
Thanks! And sorry, I wasn't completely clear on the softmax. Lines 59-60 should also be outside of the loop, as they aren't used inside.

**Comment by vicmak** [comment]
done

**Comment by neubig** [comment]
Great, thanks!

**Pull request merged**
