### PR TITLE
Exponentiated Gradient (EGTrainer) Implementation

### PR DESCRIPTION
**Pull request by duyvuleo**
This is to implement the exponentiated gradient update as in Kivinen & Warmuth (1997).
(Kivinen, Jyrki and Warmuth, Manfred K. Exponentiated gradient versus gradient descent for linear predictors. Information and Computation, 132(1):1–63, 1997)
The update formula of EG is defined as y_{t+1} := 1/Z * y_t * exp(-eta * dL(y_t)) where Z = \sum_i y_{t,i} * exp(-eta * dL(y_{t,i})).
To avoid the underflow/overflow issues, I take the log of y_{t+1}, resulting in: log(y_{t+1}) = log(y_t) - eta * dL(y_t) - logZ.
Here, logZ refers to logsumexp.

### CODE REVIEW

**Comment by neubig** [comment]
Thanks for the contribution! I haven't had time to check this carefully yet, but will try to do so soon.

**Comment by neubig** [comment]
FYI, I haven't forgotten about this. I'm just thinking about the best way to do this without duplicating the logsumexp function across multiple files. Will think about this a bit more, make some modifications, and merge shortly.

**Comment by duyvuleo** [comment]
Great! Thanks!

--
Cheers,
Vu

**Comment by duyvuleo** [comment]
Great. Thanks Graham.

--
Cheers,
Vu

**Pull request merged**
