### PR TITLE
Skip most Travis CI configs on PRs to reduce load

### PR DESCRIPTION
**Pull request by danielhers**

### CODE REVIEW

**Comment by neubig** [comment]
Thanks for fixing this quickly! I think we should keep at least one Python 2 configuration (not sure whether Mac or Linux is more common), as Python 2 often breaks when we do something silly.

**Comment by danielhers** [comment]
Added back one 2.7 setup.

**Comment by neubig** [comment]
Sorry I wasn't clear... We should do this for both pip and manual install, in case there are Python 2 specific errors in setup.py that only fail for pip or manual install.

**Comment by danielhers** [comment]
Right. Enabled pip too.

**Comment by neubig** [comment]
Thanks!

**Pull request merged**
