### PR TITLE
fix initializing RNN state with given expressions

### PR DESCRIPTION
**Pull request by yoavg**
This should solve #1223 , but I'll appreciate another set of eyes on this.

### CODE REVIEW

**Comment by neubig** [comment]
Looks good! Quick question though, what happens if you do:

    state_a = rnn.initial_state(a)
    state_b = rnn.initial_state(b)
    state_c = state_a.add_input(c)

Is `state_c` the result of calculating "a, c" or "b, c"? If I understand how Python handles references, I feel like it might be "b, c", which would be counter-intuitive. If it's "a, c" then I think this is fine to merge.

**Comment by yoavg** [comment]
Why do you think it will be `b,c`? (which reference do you think is being shared?)

**Comment by neubig** [comment]
It seems that both `state_a` and `state_b` will be pointing to `self._init_state` in the `RNNBuilder`. When you call `set_s()` when generating `state_b`, I think this might overwrite the expressions in `self._init_state`, which would affect `state_a` as well.

**Comment by yoavg** [comment]
`set_s()` adds a new state, it doesn't replace the existing one (also in cpp). 

anyhow, does this convince?
```
In [2]: m = dy.Model()

In [3]: b = dy.LSTMBuilder(1, 2, 2, m)

In [4]: x1 = dy.inputTensor([1,1])

In [5]: x2 = dy.inputTensor([2,2])

In [6]: x3 = dy.inputTensor([3,3])

In [7]: b1 = b.initial_state()

In [8]: b2 = b.initial_state([x1,x1])

In [9]: b2.add_input(x1).output().npvalue()
Out[9]: array([ 0.09968442,  0.11609479])

In [10]: b2.add_input(x1).output().npvalue()
Out[10]: array([ 0.09968442,  0.11609479])

In [11]: b3 = b.initial_state([x2,x2])

In [12]: b3.add_input(x1).output().npvalue()
Out[12]: array([ 0.04428694,  0.31293687])

In [13]: b2.add_input(x1).output().npvalue()
Out[13]: array([ 0.09968442,  0.11609479])

In [14]: b3.add_input(x1).prev() == b2
Out[14]: False

In [15]: b3.add_input(x1).prev() == b3
Out[15]: True

In [16]: b2.add_input(x1).prev() == b3
Out[16]: False

In [17]: b2.add_input(x1).prev() == b2
Out[17]: True
```

**Comment by neubig** [comment]
Thanks! LGTM then.

**Pull request merged**
