### PR TITLE
In-Memory File Read

### PR DESCRIPTION
**Pull request by vicmak**
Speed up disk IO while training

### CODE REVIEW

**Comment by neubig** [comment]
Thanks! This isn't used anywhere in the examples though. If we're going to add it, maybe it'd be nice to use it somewhere, or at least add a comment explaining it?

**Comment by yoavg** [comment]
1) How much faster is this in practice?

2) From what I recall, the python mmap API differs in Windows vs Linux/OSX. Which one is this? should be documented.

**Comment by vicmak** [comment]
1. When using large files ~ 2GB (on a VM) or more I think it worked a little faster, since the disk was the bottleneck. I did not measure it exactly.
2. @yoavg is right. This one is actually for windows. I will document the one for linux\OSx as well.

**Comment by vicmak** [comment]
Even better - I set the linux API as the default.

**Comment by neubig** [comment]
Looks good to me with the additional comment!

**Pull request merged**
