### PR TITLE
Python documentation in readthedocs

### PR DESCRIPTION
**Pull request by pmichel31415**
This pull requests addresses #169 

This is kind of a dirty trick because of the limitations of readthedocs but basically what it does is create a 'pythonized' copy of `_dynet.pyx` with empty functions that can be interpreted by sphinx (see [doc/source/doc_util.py](https://github.com/clab/dynet/compare/python_doc?expand=1#diff-5020e1e9d2db8a550c522a52223e9fae) for the script).

This also change the docstring format in `_dynet.pyx` in the more readable [napoleon](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/) format (hence the big diff in _dynet.pyx)

The documentation has been restructured slightly so that the c++ and python reference are well separated and at similar levels..

You can see the result at this url : http://dynet.readthedocs.io/en/python_doc/index.html

This ugly trick will be fixed once dynet becomes available via pip install. Until then, I believe it is a decent enough solution.

### CODE REVIEW

**Comment by yoavg** [comment]
Overall this looks very good! thanks! this is really great to have.

Two comments:
* Maybe we should list the python docs above the c++ ones? I think most users will be looking for these.
(but this is really not a major point, can also leave as is)
* More important, things starting with `_` were supposed to be private / internal. I can sort-of see why we would allow people to use `import _dynet`, but I really rather the other cases be hidden from the docs. In particular, `dynet._inputExpression`, `dynet._vecInputExpression` etc are not supposed to be used directly. People should use `dynet.vecInput` etc instead. Is there a way to hide the privates from the docs?

**Comment by pmichel31415** [comment]
OK @yoavg I addressed your 2 points.

One remark though, removing _vecInputExpression for instance hides the `.set()` method which might be useful for people who want to use a static graph.

**Comment by pmichel31415** [comment]
Also for now all functions/class need to be manually listed in `python_ref.rst` because there is no way to make custom groups. The solution would be to have e.g. all operations in a separate file, all RNNBuilders, all Optimizers, etc,..

**Comment by yoavg** [comment]
Looks good to me. 

Re the `set()` functionality, it should ideally be documented on the functions that create and return the input expressions that have a set method.

Re splitting into different files, I was not sure how to do that nicely in cython, while still allowing for `from dynet import *`. But I am not against such a change in any way.

**Comment by neubig** [comment]
Yeah, looks good to me to. Go ahead and merge if you're satisfied @pmichel31415

**Comment by pmichel31415** [comment]
Yes I'll merge now and leave the other issues for further pull requests

**Pull request merged**
