### PR TITLE
Better way to set configuration from python.

### PR DESCRIPTION
**Pull request by yoavg**
Instead of the `import _dynet/_gdynet` and then setting `DynetParams` followed by
`init`, vs `import dynet` with commandline args, we can now do:

```
    import dynet # as before
```

or:
```
    import dynet_config
    dynet_config.set_gpu()
    dynet_config.set(mem=4,random_seed=9)
    import dynet
```

### CODE REVIEW

**Comment by pmichel31415** [comment]
Thanks, that looks like a better and more intuitive way to go about it

**Comment by neubig** [comment]
This is a good idea, but we might need to rethink it once the (coming very soon) multi-device support is implemented. Do you think it's worth merging now? Or shall we think again once multi-device is working and we start doing things like removing the `libgdynet.so` library and instead just use a single library for both CPU and GPU?

**Comment by yoavg** [comment]
I'm happy waiting, but in any case it'd be nice to have a transparent mechanism for controlling the commandline arguments, esp. memory allocation, from python code.

**Comment by neubig** [comment]
OK, multi-device support is working now! It actually looks like this pull has no conflicts with the multi-device support, but perhaps we should check to make sure that nothing is broken. https://github.com/clab/dynet/pull/704

**Comment by pmichel31415** [comment]
I didn't follow the multi-device PR super closely, but does it still make sense now to have two modules `_dynet` and `_gdynet`?

Like if the module has been compiled for GPU isn't it possible to specify cpu usage in the command line? Not very familiar with the details

**Comment by neubig** [comment]
Yes, @xunzhang will probably be refactoring this in a future PR to create a single library.

**Comment by pmichel31415** [comment]
Is this still relevant with #781 ?

**Comment by xunzhang** [comment]
Oh, I added `dynet_config` in https://github.com/clab/dynet/pull/781. I think now that works and this can be closed.

**Pull request closed without merging**
