### PR TITLE
Add cumulative sum operation

### PR DESCRIPTION
**Pull request by pmichel31415**
Eigen implementation. With tests and documentation, c++ and python.

### CODE REVIEW

**Comment by neubig** [comment]
You forgot the actual files. Also, could you add the equation to the cpp doc?

**Comment by pmichel31415** [comment]
My bad! this should be fixed now

**Comment by pmichel31415** [comment]
Hmm there seems to be a compilation error on GPU. 

```
[  2%] [  2%] Building NVCC (Device) object dynet/CMakeFiles/dynet.dir/dynet_generated_gpu-merge3.cu.o
Building NVCC (Device) object dynet/CMakeFiles/dynet.dir/dynet_generated_cudnn-ops.cu.o
[  3%] Building NVCC (Device) object dynet/CMakeFiles/dynet.dir/dynet_generated_gpu-ops.cu.o
[  4%] Building NVCC (Device) object dynet/CMakeFiles/dynet.dir/dynet_generated_gpu-merge0.cu.o
[  5%] Building NVCC (Device) object dynet/CMakeFiles/dynet.dir/dynet_generated_gpu-merge1.cu.o
[  6%] Building NVCC (Device) object dynet/CMakeFiles/dynet.dir/dynet_generated_gpu-merge2.cu.o
/usr/local/include/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorScan.h(281): error: identifier "__T238" is undefined in device code
1 error detected in the compilation of "/tmp/tmpxft_00002936_00000000-21_gpu-merge2.compute_30.cpp2.i".

CMake Error at dynet_generated_gpu-merge2.cu.o.cmake:260 (message):
  Error generating file
  /home/travis/build/clab/dynet/build/dynet/CMakeFiles/dynet.dir//./dynet_generated_gpu-merge2.cu.o
```

@neubig do you have any idea where this could come from?

**Comment by neubig** [comment]
You can set CUDA_GPU_NUMFILES=0 (in CMakeLists.txt) to get a line number in the original file.

**Comment by neubig** [comment]
I was able to confirm that this is a problem, and that it's appearing in the backward pass, but I'm not sure why... You can ask the Eigen people, but the Tensor module is unsupported, and it's not guaranteed that they'd respond.

**Comment by pmichel31415** [comment]
OK Thanks for checking. My last commit pretty much confirmed that the issue seems to come from the reverse operation (on GPU).

**Comment by neubig** [comment]
Could you try splitting this up into multiple lines using scratch memory? I think that might potentially help.

**Comment by neubig** [comment]
Is this alive or dead? If dead, shall we close it?

**Comment by pmichel31415** [comment]
I'll try using scratch memory

**Comment by pmichel31415** [comment]
OK it seems like a recent pr broke the compilation on GPU on the master branch

**Comment by pmichel31415** [comment]
I can't really wrap my head around where the error comes from and I don't have time for debugging so unless someone has an idea I think we can close this one.

**Comment by pmichel31415** [comment]
Well seems like this was the problem

**Comment by neubig** [comment]
Yeah, it must've been a bug in Eigen that has since been fixed

**Pull request merged**
