### PR TITLE
Check the Cython version

### PR DESCRIPTION
**Pull request by jcyk**
Check the Cython version when installing. At least Cython version 0.23
is required.

### CODE REVIEW

**Comment by neubig** [comment]
Thanks! This is failing integration tests though, could you please take a look?

**Comment by jcyk** [comment]
eh...sorry.  It seems that it cannot find any executable of Cython.
Not sure where to find the Cython on Travis-CI platform.

**Comment by pmichel31415** [comment]
I think this is because travis isn't set up for python yet. Maybe [this](https://github.com/thearn/simple-cython-example/blob/master/.travis.yml) can help setup python and cython in the env and install part of travis.yml

**Comment by jcyk** [comment]
@pmichel31415 Actually, I am new to `cmake`.   Will you have time to fix that ? 
Look forward to learning something from it.

**Comment by jcyk** [comment]
@neubig  It passed the check on Travis-CI platform. However, as pointed out by @pblunsom travis isn't set up to test installing python module yet.

**Comment by neubig** [comment]
Great, thank you! Python not being on travis is a different problem, so this pull request is good to go.

**Pull request merged**
