### PR TITLE
allow Parameter.set_value to work on both GPU and CPU

### PR DESCRIPTION
**Pull request by jcyk**
Old version of `set_value()`  does not work on GPU. This PR may fix it.

Give a way to set the value of the parameters manually after initialization is useful.
For example, manully initialize an LSTM #529 and #636

### CODE REVIEW

**Comment by neubig** [comment]
Thanks! This is a good idea. Could you add a unit test to `test-params.cc` that ensures that this functionality is working correctly?

**Comment by neubig** [comment]
Hmm, the Python test is giving me a segfault on GPU (but not on CPU):

    test_layer_norm (test.TestOperations) ... ok
    test_grad (test.TestParameters) ... ok
    test_is_updated (test.TestParameters) ... ok
    test_set_updated (test.TestParameters) ... ok
    test_set_value (test.TestParameters) ... Segmentation fault (core dumped)

Are you able to reproduce this? If not, I can take a look.

**Comment by jcyk** [comment]
Uh. I think it is because my transfer from numpy.ndarray to vector<float> is too naive. It only works when type of value is float32 and in successive memory. There is a solution in _dynet.pyx (https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L475 )but commented with "to make more efficient ". Any idea?

**Comment by jcyk** [comment]
@neubig 
I tested on my machine, but could not reproduce the segfault, things just work fine.
It seems the direct transfer is okay at least in my machine.

**Comment by neubig** [comment]
Sorry it took so long to get back to this. I tried one more time and the segmentation fault was resolved. I'm guessing that my environment was broken when I tried before, so it looks like things are working. Thanks!

**Pull request merged**
