### PR TITLE
customable flip gradient option: C++ and python support

### PR DESCRIPTION
**Pull request by yanaiela**
regarding #318 and #321 
I added to the ```flip_gradient``` function the lambda parameter from Ganin & Lempitsky article - 
makes the reversed task objective customizable

### CODE REVIEW

**Comment by pmichel31415** [comment]
I think this is good. Maybe we should have a separate "weight gradient" expression too

**Comment by neubig** [comment]
Actually, I think @pmichel31415 's suggestion is a better one. Why don't we remove this from `flip_gradient`, and just add a `scale_gradient` operation that allows you to scale the gradient by an arbitrary scalar. Then you can call `scale_gradient(x, -lambda)` to get the same effect.

**Comment by yoavg** [comment]
How about renaming the current flip_gradient to scale_gradient, and have flip_gradient be implemented as Expression flip_gradient(x) { return scale_gradient(x, -1); }  ?

**Comment by neubig** [comment]
@yoavg Yeah, sounds good.

**Pull request merged**
