### PR TITLE
Compile with CUDA on Travis CI

### PR DESCRIPTION
**Pull request by danielhers**

### CODE REVIEW

**Comment by danielhers** [comment]
I managed to run the tests with `--dynet-devices CPU`, but still getting `CUDA failure in cudaGetDeviceCount(&nDevices)` in the initialization (presumably because there's no actual GPU even though I installed CUDA and the driver):

    #0  0x00007ffff575d51d in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #1  0x00007ffff5f28afc in dynet::initialize_gpu (params=...) at /home/daniel/workspace/dynet/dynet/cuda.cc:17
    #2  0x00007ffff5bb7fb0 in dynet::initialize (params=...) at /home/daniel/workspace/dynet/dynet/init.cc:182
    #3  0x00007ffff5bbb042 in dynet::initialize (argc=@0x7fffffffc7bc: 1, argv=@0x7fffffffc7c0: 0x6a6e00, 
        shared_parameters=shared_parameters@entry=false) at /home/daniel/workspace/dynet/dynet/init.cc:228
    #4  0x000000000040b89a in ConfigureDYNETTest::ConfigureDYNETTest (this=0x6a7c70) at /home/daniel/workspace/dynet/tests/test-dynet.cc:15

**Comment by danielhers** [comment]
I managed to pass `--dynet-devices CPU` to the tests as @neubig suggested, but some of them still fail with mysterious segfaults. Some tests do pass, though, and it's quite inconsistent. Maybe the CPU allocator breaks somehow when built with CUDA?
Do the tests work on a GPU machine?

**Comment by neubig** [comment]
They do pass on a GPU machine (at least there are no segfaults). Perhaps we can just disable the tests when compiling with CUDA on Travis for now.

**Comment by danielhers** [comment]
Done. Thanks.
(Note the AppVeyor check fails just because there's no .appveyor file yet)

**Comment by neubig** [comment]
Thanks!

**Pull request merged**
