### PR TITLE
print fw timing info on debug output

### PR DESCRIPTION
**Pull request by yoavg**
This adds the ability to measure and print out the cumulative time spent on different node types when using forward, on either the autobatch or non-autobatched executors. It is helpful to (a) see which ops benefit most from autobatching on different platforms (b) helps finding bottlenecks and slow ops in general.

### CODE REVIEW

**Comment by neubig** [comment]
This looks good, and I think we can merge if you'd like. One thing it might be worth thinking about is whether we can make this do aggregate statistics instead of per-execution statistics. For example, make the NamedTimer global, then have it print statistics when its destructor is called?

**Comment by yoavg** [comment]
Sure, I can make it aggregate across executions. I kinda liked it this way because it also allows you to isolate different calls to forward in an incremental setup, but it's not a strong preference.

**Comment by neubig** [comment]
OK, cool. We could also get the best of both worlds by making it possible to reset/print from the global NamedTimer on the user's side, so the user could choose to print/reset after each call to forward.

**Comment by yoavg** [comment]
where would be a good place to put the global timer?

**Comment by neubig** [comment]
`globals.{h,cc}`

**Pull request merged**
