### PR TITLE
Dynet 1296. cuRAND support for multiple GPUs.

### PR DESCRIPTION
**Pull request by xunzhang**
Address https://github.com/clab/dynet/issues/1296. I removed the global curandeng.

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @neubig @speedcell4

**Comment by neubig** [comment]
Assuming that this has been tested, I think you can go ahead and merge. Thanks!

**Comment by xunzhang** [comment]
I have tested @speedcell4 's script and tested xor-multidevice example.

**Comment by xunzhang** [comment]
@speedcell4 Could you help test it?

**Comment by xunzhang** [comment]
Gonna to merge this now.

**Pull request merged**
