### PR TITLE
fix parameter set_value

### PR DESCRIPTION
**Pull request by chunyang-wen**
Support both np.ndarray and python list used in the `parameter.set_value`

```python
import dynet

m = dynet.ParameterCollection()
pX = m.add_parameters((2,))
pY = m.add_parameters((2,))

pX.set_value([2,1])
p = dynet.parameter(pX)
print p.value()

pY.set_value(np.array([2,1]))
q = dynet.parameter(pY)
print q.value()
```

### CODE REVIEW

**Comment by chunyang-wen** [comment]
#1002

**Comment by pmichel31415** [comment]
I'm not sure which is faster but `np.asarray` should do the same

**Comment by chunyang-wen** [comment]
@pmichel31415 I have searched the doc. `np.array` default will make a copy, so under circumstance it will be slower. Replace it with `np.asarray'.

**Comment by chunyang-wen** [comment]
@neubig Ping.

**Comment by neubig** [comment]
Thanks!

**Pull request merged**
